### ISSUE TITLE
Exception when stopping process

### ISSUE THREAD

**Issue by alexwalterbos** [alexwalterbos/image-reconstruction#13]
When I use the `stop` button, the debug complains about an exception not being caught.

![image](https://cloud.githubusercontent.com/assets/1196596/3142576/b3d02672-e9c8-11e3-8bd0-c0d27a6abf6c.png)

**Comment by festen** [comment]
This is actually a visual studio problem. It occurs because one thread throws an exception and doesn't catch it, after that the exception wil go to the TPL layer and is catcher by the awaiting function.

Two ways to fix:
1) Go to `Tools > Options > Debug > "Just My Code"` and make sure it is disabled. This ensures that the program doesn't break on thrown async exceptions
2) Run the program without a debugger at all. If you are not debugging, you can run without debugger. Just go to the build .exe file or go to `Debug > "Run without debugger"` or hit `CTRL + F5`

Curious about the details? Read the source!
source: http://blogs.msdn.com/b/pfxteam/archive/2010/01/11/9946736.aspx

**Comment by alexwalterbos** [comment]
Thanks!
